# Generated by Django 4.2.2 on 2023-08-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=5000)),
                ('thumbnail', models.ImageField(upload_to='blog/thumbnail')),
                ('category', models.CharField(choices=[('general', 'General'), ('science', 'Science'), ('english', 'English'), ('maths', 'Maths'), ('sst', 'SST'), ('gaming', 'Gaming'), ('news', 'News'), ('announcements', 'Announcements'), ('sports', 'Sports'), ('cooking', 'Cooking'), ('lifestyle', 'Lifestyle'), ('news', 'News')], default='general', max_length=20)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
