# Generated by Django 4.2.4 on 2023-08-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('css', models.ImageField(upload_to='blog/css')),
                ('img', models.ImageField(upload_to='blog/img')),
            ],
        ),
    ]
