# Generated by Django 4.2.4 on 2023-08-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='css',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='img',
        ),
    ]
